// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7xxW8QJFA0gaKX4AhHN-nY-DNFItXPbQ',
    appId: '1:498385460864:web:12438b57522644996b9065',
    messagingSenderId: '498385460864',
    projectId: 'project-team-final',
    authDomain: 'project-team-final.firebaseapp.com',
    storageBucket: 'project-team-final.appspot.com',
    measurementId: 'G-LNS2274ZFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItBIcQ8GqbtEbtC-ryK8kOc-GPc34AbM',
    appId: '1:498385460864:android:6c6dd6bd5f886d826b9065',
    messagingSenderId: '498385460864',
    projectId: 'project-team-final',
    storageBucket: 'project-team-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnQsuPmZN0sGU8o8bIKHiuzz9FZ3tqTdU',
    appId: '1:498385460864:ios:692dc2ebf345b9c56b9065',
    messagingSenderId: '498385460864',
    projectId: 'project-team-final',
    storageBucket: 'project-team-final.appspot.com',
    iosClientId: '498385460864-n7g4h447d4s1s091dpvlt7m6utk7u3so.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamProjectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnQsuPmZN0sGU8o8bIKHiuzz9FZ3tqTdU',
    appId: '1:498385460864:ios:692dc2ebf345b9c56b9065',
    messagingSenderId: '498385460864',
    projectId: 'project-team-final',
    storageBucket: 'project-team-final.appspot.com',
    iosClientId: '498385460864-n7g4h447d4s1s091dpvlt7m6utk7u3so.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamProjectFinal',
  );
}
